### ISSUE TITLE
Fix expressions evaluating to `null`

### ISSUE THREAD

**Issue by praisethemoon** [unlimitedsoftwareworks/type-c#5]
The parser `parsefuncs.ts` does allow expressions to evaluate to null, while this is not documented in the types, it is a thing.
This is used primarily for `return` and `yield` which may not have an expression to return.

The parser needs to pass an option flag `{allowNull}` to make sure to catch cases where it is allowed to return null and where it is not.

This will also help intellisnse (hopefully)

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the parseExpression function to include an allowNull option. This change helps differentiate between cases where null expressions are allowed (like in return and yield statements) and where they are not. Also updated related functions to pass this option appropriately.

You can review changes in this commit: https://github.com/lattaai13/unlimitedsoftwareworks-type-c-5/commit/6118faf879edd1d5b8f6778b82a566ebaf8cf471.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
